language: node_js
node_js:
  - 14
notifications:
  webhooks:
    urls:
      - http://test.binaryfissiongames.com/travisci
    on_cancel:  never # default: always
    on_error:   never # default: always
    on_failure: never # default: always
